services:
  mysql:
    image: mysql:8.0.24
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  rails:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - mysql